In [25]:
import pandas as pd
import os

In [26]:
mainpath = "E:\Trading\Trading\AnalisisLevels"
filename = "FtxADAPERP.csv"
fullpath = os.path.join(mainpath, filename)

In [27]:
data = pd.read_csv(fullpath)

In [28]:
data.head()

,Id,Price,Time,State,activo,UTDate,ValidationDate,TimeFrame,Color,High,Stop,Fill,Tested,R1,R2,RMaxima,DateFill,DateStop,DateUltimaR
0,1,0.035910,Wed Oct 23 2019 02:00:00 GMT+0200 (hora de ver...,untested,1,0,Sat Dec 14 2019 01:00:00 GMT+0100 (hora estánd...,1w,orange,0,0.036200,1,0,0,0,0.086207,Mon Jan 06 2020 10:33:00 GMT+0100 (hora estánd...,Mon Jan 06 2020 10:49:00 GMT+0100 (hora estánd...,Thu Jan 01 1970 01:00:00 GMT+0100 (hora estánd...
1,2,0.035910,Wed Oct 23 2019 22:00:00 GMT+0200 (hora de ver...,untested,1,1574420400000000000,Fri Nov 22 2019 09:00:00 GMT+0100 (hora estánd...,4h,green,0,0.036245,0,1,0,0,0.000000,Thu Jan 01 1970 01:00:00 GMT+0100 (hora estánd...,Thu Jan 01 1970 01:00:00 GMT+0100 (hora estánd...,Thu Jan 01 1970 01:00:00 GMT+0100 (hora estánd...
2,3,0.035910,Thu Oct 24 2019 00:00:00 GMT+0200 (hora de ver...,untested,1,1574418420000000000,Fri Nov 22 2019 11:00:00 GMT+0100 (hora estánd...,1h,blue,0,0.036375,0,1,0,0,0.000000,Thu Jan 01 1970 01:00:00 GMT+0100 (hora estánd...,Thu Jan 01 1970 01:00:00 GMT+0100 (hora estánd...,Thu Jan 01 1970 01:00:00 GMT+0100 (hora estánd...
3,4,0.035910,Thu Oct 24 2019 02:00:00 GMT+0200 (hora de ver...,untested,1,1574611200000000000,Sun Nov 24 2019 01:00:00 GMT+0100 (hora estánd...,1d,yellow,0,0.035930,0,1,0,0,0.000000,Thu Jan 01 1970 01:00:00 GMT+0100 (hora estánd...,Thu Jan 01 1970 01:00:00 GMT+0100 (hora estánd...,Thu Jan 01 1970 01:00:00 GMT+0100 (hora estánd...
4,5,0.036875,Thu Oct 24 2019 02:00:00 GMT+0200 (hora de ver...,untested,1,1571906340000000000,Thu Oct 24 2019 10:00:00 GMT+0200 (hora de ver...,1h,blue,1,0.035965,0,1,0,0,0.000000,Thu Jan 01 1970 01:00:00 GMT+0100 (hora estánd...,Thu Jan 01 1970 01:00:00 GMT+0100 (hora estánd...,Thu Jan 01 1970 01:00:00 GMT+0100 (hora estánd...

In [29]:
data.describe()

,Id,Price,activo,UTDate,High,Stop,Fill,Tested,R1,R2,RMaxima
count,12428.000000,12428.000000,12428.000000,1.242800e+04,12428.000000,12428.000000,12428.000000,12428.000000,12428.000000,12428.000000,12428.000000
mean,6214.500000,0.782481,0.943032,7.945107e+17,0.500241,0.741805,0.386949,0.548761,0.198825,0.132845,24.777278
std,3587.798907,0.761488,0.231791,8.083741e+17,0.500020,0.754353,0.487071,0.497637,0.399132,0.339421,432.471176
min,1.000000,0.017580,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,3107.750000,0.091470,1.000000,0.000000e+00,0.000000,0.076080,0.000000,0.000000,0.000000,0.000000,0.000000
50%,6214.500000,0.569935,1.000000,0.000000e+00,1.000000,0.473862,0.000000,1.000000,0.000000,0.000000,0.000000
75%,9321.250000,1.294084,1.000000,1.616830e+18,1.000000,1.270118,1.000000,1.000000,0.000000,0.000000,0.592306
max,12428.000000,3.111830,1.000000,1.655045e+18,1.000000,3.057890,1.000000,1.000000,1.000000,1.000000,19146.375000

In [30]:
data2 = data[data['Fill'] == 1]
data2['PorcentajeStop'] = (abs(data2['Price'] - data2['Stop']) / data2['Price']) * 100

data2.head()

C:\Users\Enrique\AppData\Local\Temp/ipykernel_19064/2808033152.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data2['PorcentajeStop'] = (abs(data2['Price'] - data2['Stop']) / data2['Price']) * 100

,Id,Price,Time,State,activo,UTDate,ValidationDate,TimeFrame,Color,High,Stop,Fill,Tested,R1,R2,RMaxima,DateFill,DateStop,DateUltimaR,PorcentajeStop
0,1,0.035910,Wed Oct 23 2019 02:00:00 GMT+0200 (hora de ver...,untested,1,0,Sat Dec 14 2019 01:00:00 GMT+0100 (hora estánd...,1w,orange,0,0.036200,1,0,0,0,0.086207,Mon Jan 06 2020 10:33:00 GMT+0100 (hora estánd...,Mon Jan 06 2020 10:49:00 GMT+0100 (hora estánd...,Thu Jan 01 1970 01:00:00 GMT+0100 (hora estánd...,0.807574
8,9,0.036565,Thu Oct 24 2019 07:00:00 GMT+0200 (hora de ver...,untested,1,0,Thu Oct 24 2019 09:00:00 GMT+0200 (hora de ver...,1h,blue,1,0.035965,1,0,1,1,15.925000,Thu Oct 24 2019 10:04:00 GMT+0200 (hora de ver...,Fri Nov 22 2019 11:04:00 GMT+0100 (hora estánd...,Thu Oct 24 2019 16:07:00 GMT+0200 (hora de ver...,1.640913
10,11,0.038005,Thu Oct 24 2019 17:00:00 GMT+0200 (hora de ver...,untested,1,0,Fri Oct 25 2019 12:00:00 GMT+0200 (hora de ver...,1h,blue,1,0.037200,1,0,1,1,10.080745,Fri Oct 25 2019 13:04:00 GMT+0200 (hora de ver...,Thu Nov 21 2019 16:04:00 GMT+0100 (hora estánd...,Fri Oct 25 2019 17:47:00 GMT+0200 (hora de ver...,2.118142
15,16,0.037200,Fri Oct 25 2019 06:00:00 GMT+0200 (hora de ver...,untested,1,0,Fri Nov 22 2019 09:00:00 GMT+0100 (hora estánd...,4h,green,0,0.037440,1,0,0,0,0.541667,Fri Nov 22 2019 20:10:00 GMT+0100 (hora estánd...,Fri Nov 22 2019 20:15:00 GMT+0100 (hora estánd...,Thu Jan 01 1970 01:00:00 GMT+0100 (hora estánd...,0.645161
17,18,0.037200,Fri Oct 25 2019 07:00:00 GMT+0200 (hora de ver...,untested,1,0,Fri Nov 22 2019 10:00:00 GMT+0100 (hora estánd...,1h,blue,0,0.037440,1,0,0,0,0.541667,Fri Nov 22 2019 20:10:00 GMT+0100 (hora estánd...,Fri Nov 22 2019 20:15:00 GMT+0100 (hora estánd...,Thu Jan 01 1970 01:00:00 GMT+0100 (hora estánd...,0.645161

In [31]:
data2.describe()

,Id,Price,activo,UTDate,High,Stop,Fill,Tested,R1,R2,RMaxima,PorcentajeStop
count,4809.000000,4809.000000,4809.0,4809.0,4809.000000,4809.000000,4809.0,4809.0,4809.000000,4809.000000,4809.000000,4809.000000
mean,5894.153878,0.749391,1.0,0.0,0.517363,0.748643,1.0,0.0,0.513828,0.343315,64.032441,1.270048
std,3590.064282,0.766328,0.0,0.0,0.499750,0.765285,0.0,0.0,0.499861,0.474865,693.466998,1.672128
min,1.000000,0.021590,1.0,0.0,0.000000,0.000000,1.0,0.0,0.000000,0.000000,0.000000,0.006930
25%,2731.000000,0.079930,1.0,0.0,0.000000,0.080430,1.0,0.0,0.000000,0.000000,0.350877,0.628471
50%,5814.000000,0.397900,1.0,0.0,1.000000,0.390420,1.0,0.0,1.000000,0.000000,1.042896,1.093578
75%,8887.000000,1.281985,1.0,0.0,1.000000,1.275855,1.0,0.0,1.000000,1.000000,3.194737,1.659450
max,12423.000000,3.020100,1.0,0.0,1.000000,3.057890,1.0,0.0,1.000000,1.000000,19146.375000,100.000000

In [37]:
# data3 = data2[data2['RMaxima'] >= 3 ]
data3 = data2[data2['PorcentajeStop'] <= 3]
data3 = data3[data3['PorcentajeStop'] >= 0.3]
data3.describe()

,Id,Price,activo,UTDate,High,Stop,Fill,Tested,R1,R2,RMaxima,PorcentajeStop
count,4167.000000,4167.000000,4167.0,4167.0,4167.000000,4167.000000,4167.0,4167.0,4167.000000,4167.000000,4167.000000,4167.000000
mean,5886.946724,0.740924,1.0,0.0,0.531317,0.739876,1.0,0.0,0.513079,0.342693,70.380690,1.232330
std,3606.569397,0.760151,0.0,0.0,0.499078,0.758568,0.0,0.0,0.499889,0.474667,741.269380,0.610805
min,1.000000,0.021590,1.0,0.0,0.000000,0.022175,1.0,0.0,0.000000,0.000000,0.000000,0.300293
25%,2724.000000,0.079845,1.0,0.0,0.000000,0.079692,1.0,0.0,0.000000,0.000000,0.377358,0.738067
50%,5778.000000,0.377115,1.0,0.0,1.000000,0.376005,1.0,0.0,1.000000,0.000000,1.038144,1.136267
75%,8889.500000,1.273827,1.0,0.0,1.000000,1.267192,1.0,0.0,1.000000,1.000000,3.224490,1.634671
max,12423.000000,3.020100,1.0,0.0,1.000000,3.057890,1.0,0.0,1.000000,1.000000,19146.375000,2.997810

In [33]:
data4 = data[data['TimeFrame'] == '1w']
data4.head()

,Id,Price,Time,State,activo,UTDate,ValidationDate,TimeFrame,Color,High,Stop,Fill,Tested,R1,R2,RMaxima,DateFill,DateStop,DateUltimaR
0,1,0.035910,Wed Oct 23 2019 02:00:00 GMT+0200 (hora de ver...,untested,1,0,Sat Dec 14 2019 01:00:00 GMT+0100 (hora estánd...,1w,orange,0,0.036200,1,0,0,0,0.086207,Mon Jan 06 2020 10:33:00 GMT+0100 (hora estánd...,Mon Jan 06 2020 10:49:00 GMT+0100 (hora estánd...,Thu Jan 01 1970 01:00:00 GMT+0100 (hora estánd...
128,129,0.046100,Sat Nov 02 2019 01:00:00 GMT+0100 (hora estánd...,untested,1,0,Sat Jan 25 2020 01:00:00 GMT+0100 (hora estánd...,1w,orange,1,0.045950,1,0,1,0,1.200000,Sun Mar 01 2020 17:45:00 GMT+0100 (hora estánd...,Sun Mar 01 2020 17:46:00 GMT+0100 (hora estánd...,Sun Mar 01 2020 17:45:00 GMT+0100 (hora estánd...
316,317,0.033000,Sat Nov 23 2019 01:00:00 GMT+0100 (hora estánd...,untested,1,1577448000000000000,Sat Dec 21 2019 01:00:00 GMT+0100 (hora estánd...,1w,orange,0,0.033245,0,1,0,0,0.000000,Thu Jan 01 1970 01:00:00 GMT+0100 (hora estánd...,Thu Jan 01 1970 01:00:00 GMT+0100 (hora estánd...,Thu Jan 01 1970 01:00:00 GMT+0100 (hora estánd...
413,414,0.042165,Sat Nov 30 2019 01:00:00 GMT+0100 (hora estánd...,untested,1,1579262400000000000,Sat Jan 11 2020 01:00:00 GMT+0100 (hora estánd...,1w,orange,1,0.042155,0,1,0,0,0.000000,Thu Jan 01 1970 01:00:00 GMT+0100 (hora estánd...,Thu Jan 01 1970 01:00:00 GMT+0100 (hora estánd...,Thu Jan 01 1970 01:00:00 GMT+0100 (hora estánd...
532,533,0.030405,Sat Dec 14 2019 01:00:00 GMT+0100 (hora estánd...,untested,1,1584028800000000000,Sat Mar 07 2020 01:00:00 GMT+0100 (hora estánd...,1w,orange,0,0.030490,0,1,0,0,0.000000,Thu Jan 01 1970 01:00:00 GMT+0100 (hora estánd...,Thu Jan 01 1970 01:00:00 GMT+0100 (hora estánd...,Thu Jan 01 1970 01:00:00 GMT+0100 (hora estánd...

In [34]:
data7 = data2[data2['High']==0]
data7 = data7[data7['TimeFrame']=='4h']
data7 = data7[data7['PorcentajeStop'] <= 10]
data7.describe()

,Id,Price,activo,UTDate,High,Stop,Fill,Tested,R1,R2,RMaxima,PorcentajeStop
count,324.000000,324.000000,324.0,324.0,324.0,324.000000,324.0,324.0,324.000000,324.000000,324.000000,324.000000
mean,5752.666667,0.722078,1.0,0.0,0.0,0.731216,1.0,0.0,0.558642,0.339506,6.734996,1.312468
std,3747.943315,0.749746,0.0,0.0,0.0,0.760271,0.0,0.0,0.497317,0.474274,25.061564,1.176811
min,16.000000,0.023985,1.0,0.0,0.0,0.024515,1.0,0.0,0.000000,0.000000,0.000000,0.042485
25%,2273.250000,0.056993,1.0,0.0,0.0,0.057405,1.0,0.0,0.000000,0.000000,0.396855,0.529766
50%,5604.500000,0.346740,1.0,0.0,0.0,0.349760,1.0,0.0,1.000000,0.000000,1.230402,0.969373
75%,9100.500000,1.209271,1.0,0.0,0.0,1.231203,1.0,0.0,1.000000,1.000000,3.234761,1.664142
max,12408.000000,2.830505,1.0,0.0,0.0,2.866275,1.0,0.0,1.000000,1.000000,337.061785,7.169873