In [128]:
import pandas as pd
import os

In [129]:
mainpath = "E:\Trading\Trading\AnalisisLevels"
filename = "FtxADAPERP.csv"
fullpath = os.path.join(mainpath, filename)

In [130]:
data = pd.read_csv(fullpath)

In [131]:
data.head()

,Id,Price,Time,State,activo,UTDate,ValidationDate,TimeFrame,Color,High,Stop,Fill,Tested,R1,R2,RMaxima,DateFill,DateStop,DateUltimaR
0,1,0.035849,Wed Oct 23 2019 02:00:00 GMT+0200 (hora de ver...,Stop repetido,1,0,Sat Dec 14 2019 01:00:00 GMT+0100 (hora estánd...,1w,orange,0,0.036262,0,1,0,0,0.0,Thu Jan 01 1970 01:00:00 GMT+0100 (hora estánd...,Thu Jan 01 1970 01:00:00 GMT+0100 (hora estánd...,Thu Jan 01 1970 01:00:00 GMT+0100 (hora estánd...
1,2,0.035849,Wed Oct 23 2019 22:00:00 GMT+0200 (hora de ver...,untested,1,1574607600000000000,Sun Nov 24 2019 13:00:00 GMT+0100 (hora estánd...,4h,green,0,0.035921,0,1,0,0,0.0,Thu Jan 01 1970 01:00:00 GMT+0100 (hora estánd...,Thu Jan 01 1970 01:00:00 GMT+0100 (hora estánd...,Thu Jan 01 1970 01:00:00 GMT+0100 (hora estánd...
2,3,0.035849,Thu Oct 24 2019 00:00:00 GMT+0200 (hora de ver...,Stop repetido,1,0,Fri Nov 22 2019 11:00:00 GMT+0100 (hora estánd...,1h,blue,0,0.036437,0,1,0,0,0.0,Thu Jan 01 1970 01:00:00 GMT+0100 (hora estánd...,Thu Jan 01 1970 01:00:00 GMT+0100 (hora estánd...,Thu Jan 01 1970 01:00:00 GMT+0100 (hora estánd...
3,4,0.035849,Thu Oct 24 2019 02:00:00 GMT+0200 (hora de ver...,untested,1,1574629200000000000,Sun Nov 24 2019 01:00:00 GMT+0100 (hora estánd...,1d,yellow,0,0.035991,0,1,0,0,0.0,Thu Jan 01 1970 01:00:00 GMT+0100 (hora estánd...,Thu Jan 01 1970 01:00:00 GMT+0100 (hora estánd...,Thu Jan 01 1970 01:00:00 GMT+0100 (hora estánd...
4,5,0.036938,Thu Oct 24 2019 02:00:00 GMT+0200 (hora de ver...,Stop repetido,1,0,Thu Oct 24 2019 10:00:00 GMT+0200 (hora de ver...,1h,blue,1,0.035904,0,1,0,0,0.0,Thu Jan 01 1970 01:00:00 GMT+0100 (hora estánd...,Thu Jan 01 1970 01:00:00 GMT+0100 (hora estánd...,Thu Jan 01 1970 01:00:00 GMT+0100 (hora estánd...

In [132]:
data.describe()

,Id,Price,activo,UTDate,High,Stop,Fill,Tested,R1,R2,RMaxima
count,12440.000000,12440.000000,12440.000000,1.244000e+04,12440.000000,12440.000000,12440.000000,12440.000000,12440.000000,12440.000000,12440.000000
mean,6220.500000,0.782208,0.937621,2.220587e+17,0.500161,0.737985,0.361495,0.570981,0.181109,0.120418,14.286947
std,3591.263009,0.761283,0.241853,5.563345e+17,0.500020,0.753018,0.480453,0.494956,0.385124,0.325463,349.409125
min,1.000000,0.017550,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,3110.750000,0.091504,1.000000,0.000000e+00,0.000000,0.072196,0.000000,0.000000,0.000000,0.000000,0.000000
50%,6220.500000,0.568918,1.000000,0.000000e+00,1.000000,0.456118,0.000000,1.000000,0.000000,0.000000,0.000000
75%,9330.250000,1.293301,1.000000,0.000000e+00,1.000000,1.269595,1.000000,1.000000,0.000000,0.000000,0.477218
max,12440.000000,3.117120,1.000000,1.655135e+18,1.000000,3.063088,1.000000,1.000000,1.000000,1.000000,28181.467705

In [133]:
data2 = data[data['Fill'] == 1]
data2['PorcentajeStop'] = (abs(data2['Price'] - data2['Stop']) / data2['Price']) * 100

data2.head()

C:\Users\Enrique\AppData\Local\Temp/ipykernel_17660/2808033152.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data2['PorcentajeStop'] = (abs(data2['Price'] - data2['Stop']) / data2['Price']) * 100

,Id,Price,Time,State,activo,UTDate,ValidationDate,TimeFrame,Color,High,Stop,Fill,Tested,R1,R2,RMaxima,DateFill,DateStop,DateUltimaR,PorcentajeStop
8,9,0.036627,Thu Oct 24 2019 07:00:00 GMT+0200 (hora de ver...,untested,1,0,Thu Oct 24 2019 10:00:00 GMT+0200 (hora de ver...,1h,blue,1,0.035904,1,0,1,1,2.934932,Fri Nov 22 2019 08:03:00 GMT+0100 (hora estánd...,Fri Nov 22 2019 11:04:00 GMT+0100 (hora estánd...,Fri Nov 22 2019 09:03:00 GMT+0100 (hora estánd...,1.974767
10,11,0.038070,Thu Oct 24 2019 17:00:00 GMT+0200 (hora de ver...,untested,1,0,Fri Oct 25 2019 13:00:00 GMT+0200 (hora de ver...,1h,blue,1,0.037851,1,0,1,0,1.348426,Thu Nov 21 2019 16:00:00 GMT+0100 (hora estánd...,Thu Nov 21 2019 16:01:00 GMT+0100 (hora estánd...,Thu Nov 21 2019 16:00:00 GMT+0100 (hora estánd...,0.575430
14,15,0.037326,Fri Oct 25 2019 03:00:00 GMT+0200 (hora de ver...,untested,1,0,Fri Nov 22 2019 10:00:00 GMT+0100 (hora estánd...,1h,blue,0,0.037504,1,0,0,0,0.600623,Fri Nov 22 2019 20:15:00 GMT+0100 (hora estánd...,Fri Nov 22 2019 20:18:00 GMT+0100 (hora estánd...,Thu Jan 01 1970 01:00:00 GMT+0100 (hora estánd...,0.474760
16,17,0.037854,Fri Oct 25 2019 06:00:00 GMT+0200 (hora de ver...,untested,1,0,Fri Oct 25 2019 12:00:00 GMT+0200 (hora de ver...,1h,blue,1,0.037137,1,0,0,0,0.231026,Thu Nov 21 2019 16:01:00 GMT+0100 (hora estánd...,Thu Nov 21 2019 16:04:00 GMT+0100 (hora estánd...,Thu Jan 01 1970 01:00:00 GMT+0100 (hora estánd...,1.895383
18,19,0.041791,Fri Oct 25 2019 17:00:00 GMT+0200 (hora de ver...,untested,1,0,Sat Oct 26 2019 02:00:00 GMT+0200 (hora de ver...,1h,blue,1,0.000000,1,0,1,1,73.461862,Wed Oct 23 2019 20:53:00 GMT+0200 (hora de ver...,Thu Jan 01 1970 01:00:00 GMT+0100 (hora estánd...,Wed Jul 08 2020 03:12:00 GMT+0200 (hora de ver...,100.000000

In [134]:
data2.describe()

,Id,Price,activo,UTDate,High,Stop,Fill,Tested,R1,R2,RMaxima,PorcentajeStop
count,4497.000000,4497.000000,4497.0,4497.0,4497.000000,4497.000000,4497.0,4497.0,4497.000000,4497.000000,4497.000000,4497.000000
mean,6321.937514,0.794307,1.0,0.0,0.502335,0.794068,1.0,0.0,0.501001,0.333111,39.521820,1.066622
std,3511.423084,0.744482,0.0,0.0,0.500050,0.744343,0.0,0.0,0.500055,0.471378,580.325395,1.610647
min,9.000000,0.021553,1.0,0.0,0.000000,0.000000,1.0,0.0,0.000000,0.000000,0.000000,0.170028
25%,3384.000000,0.096544,1.0,0.0,0.000000,0.096268,1.0,0.0,0.000000,0.000000,0.355509,0.536922
50%,6293.000000,0.630142,1.0,0.0,1.000000,0.630926,1.0,0.0,1.000000,0.000000,1.003313,0.927298
75%,9315.000000,1.308077,1.0,0.0,1.000000,1.308170,1.0,0.0,1.000000,1.000000,2.985577,1.427020
max,12436.000000,3.060419,1.0,0.0,1.000000,3.063088,1.0,0.0,1.000000,1.000000,28181.467705,100.000000

In [135]:
# data3 = data2[data2['RMaxima'] >= 3 ]
data3 = data2[data2['PorcentajeStop'] <= 3.17]
data3 = data3[data3['PorcentajeStop'] >= 0.2]
#data3 = data3[data3['TimeFrame'] == '1h']
#data5 = data3.groupby("Stop")
# data3 = data3[data3['PorcentajeStop'] < 100]
#ata5.describe()

In [136]:

data4 = data[data['TimeFrame'] == '1w']
#data4.head()
data3.describe()

,Id,Price,activo,UTDate,High,Stop,Fill,Tested,R1,R2,RMaxima,PorcentajeStop
count,4359.000000,4359.000000,4359.0,4359.0,4359.000000,4359.000000,4359.0,4359.0,4359.000000,4359.000000,4359.000000,4359.000000
mean,6315.947694,0.794676,1.0,0.0,0.501721,0.794477,1.0,0.0,0.498738,0.330351,40.388313,1.049242
std,3517.169527,0.745613,0.0,0.0,0.500054,0.745566,0.0,0.0,0.500056,0.470393,589.260481,0.606968
min,9.000000,0.021553,1.0,0.0,0.000000,0.022213,1.0,0.0,0.000000,0.000000,0.000000,0.200390
25%,3363.000000,0.096273,1.0,0.0,0.000000,0.095765,1.0,0.0,0.000000,0.000000,0.359394,0.560016
50%,6293.000000,0.631417,1.0,0.0,1.000000,0.632009,1.0,0.0,0.000000,0.000000,0.996802,0.939561
75%,9324.500000,1.306744,1.0,0.0,1.000000,1.305876,1.0,0.0,1.000000,1.000000,2.985207,1.429379
max,12436.000000,3.060419,1.0,0.0,1.000000,3.063088,1.0,0.0,1.000000,1.000000,28181.467705,3.154225

In [137]:
data7 = data2[data2['High']==0]
data7 = data7[data7['TimeFrame']=='4h']
data7 = data7[data7['PorcentajeStop'] <= 10]
data7.describe()

,Id,Price,activo,UTDate,High,Stop,Fill,Tested,R1,R2,RMaxima,PorcentajeStop
count,242.000000,242.000000,242.0,242.0,242.0,242.000000,242.0,242.0,242.000000,242.000000,242.000000,242.000000
mean,6082.301653,0.752498,1.0,0.0,0.0,0.758986,1.0,0.0,0.491736,0.330579,3.443585,0.876385
std,3563.126644,0.744103,0.0,0.0,0.0,0.751130,0.0,0.0,0.500968,0.471396,7.403252,0.615611
min,99.000000,0.023944,1.0,0.0,0.0,0.024557,1.0,0.0,0.000000,0.000000,0.000000,0.170062
25%,3312.000000,0.093275,1.0,0.0,0.0,0.094018,1.0,0.0,0.000000,0.000000,0.394818,0.426445
50%,5971.000000,0.456974,1.0,0.0,0.0,0.460121,1.0,0.0,0.000000,0.000000,0.962981,0.758985
75%,9165.500000,1.317318,1.0,0.0,0.0,1.324495,1.0,0.0,1.000000,1.000000,3.106879,1.103114
max,12397.000000,2.780266,1.0,0.0,0.0,2.840060,1.0,0.0,1.000000,1.000000,77.707887,3.465916