In [64]:
import pandas as pd
import os

In [65]:
mainpath = "E:\Trading\Trading\AnalisisLevels"
filename = "FtxADAPERP.csv"
fullpath = os.path.join(mainpath, filename)

In [66]:
data = pd.read_csv(fullpath)

In [67]:
data.head()

,Id,Price,Time,State,activo,UTDate,ValidationDate,TimeFrame,Color,High,Stop,Fill,Tested,R1,R2,RMaxima,DateFill,DateStop,DateUltimaR
0,1,0.035910,Wed Oct 23 2019 02:00:00 GMT+0200 (hora de ver...,untested,1,1576339320000000000,Sat Dec 14 2019 01:00:00 GMT+0100 (hora estánd...,1w,orange,0,0.042165,0,1,0,0,0.0,Thu Jan 01 1970 01:00:00 GMT+0100 (hora estánd...,Thu Jan 01 1970 01:00:00 GMT+0100 (hora estánd...,Thu Jan 01 1970 01:00:00 GMT+0100 (hora estánd...
1,2,0.035910,Wed Oct 23 2019 22:00:00 GMT+0200 (hora de ver...,untested,1,1574417100000000000,Fri Nov 22 2019 09:00:00 GMT+0100 (hora estánd...,4h,green,0,0.038940,0,1,0,0,0.0,Thu Jan 01 1970 01:00:00 GMT+0100 (hora estánd...,Thu Jan 01 1970 01:00:00 GMT+0100 (hora estánd...,Thu Jan 01 1970 01:00:00 GMT+0100 (hora estánd...
2,3,0.035910,Thu Oct 24 2019 02:00:00 GMT+0200 (hora de ver...,untested,1,1574607300000000000,Sun Nov 24 2019 01:00:00 GMT+0100 (hora estánd...,1d,yellow,0,0.038820,0,1,0,0,0.0,Thu Jan 01 1970 01:00:00 GMT+0100 (hora estánd...,Thu Jan 01 1970 01:00:00 GMT+0100 (hora estánd...,Thu Jan 01 1970 01:00:00 GMT+0100 (hora estánd...
3,4,0.036875,Thu Oct 24 2019 02:00:00 GMT+0200 (hora de ver...,untested,1,1571906340000000000,Thu Oct 24 2019 10:00:00 GMT+0200 (hora de ver...,4h,green,1,0.035965,0,1,0,0,0.0,Thu Jan 01 1970 01:00:00 GMT+0100 (hora estánd...,Thu Jan 01 1970 01:00:00 GMT+0100 (hora estánd...,Thu Jan 01 1970 01:00:00 GMT+0100 (hora estánd...
4,5,0.035965,Thu Oct 24 2019 06:00:00 GMT+0200 (hora de ver...,untested,1,1574417100000000000,Fri Nov 22 2019 09:00:00 GMT+0100 (hora estánd...,4h,green,0,0.038940,0,1,0,0,0.0,Thu Jan 01 1970 01:00:00 GMT+0100 (hora estánd...,Thu Jan 01 1970 01:00:00 GMT+0100 (hora estánd...,Thu Jan 01 1970 01:00:00 GMT+0100 (hora estánd...

In [68]:
data.describe()

,Id,Price,activo,UTDate,High,Stop,Fill,Tested,R1,R2,RMaxima
count,6078.0000,6078.000000,6078.000000,6.078000e+03,6078.000000,6078.000000,6078.000000,6078.000000,6078.000000,6078.000000,6078.000000
mean,3039.5000,0.801646,0.923166,1.190317e+18,0.499671,0.750193,0.033070,0.887298,0.019743,0.014972,4.994969
std,1754.7118,0.756089,0.266351,7.118160e+17,0.500041,0.752975,0.178834,0.316254,0.139128,0.121451,136.276072
min,1.0000,0.017580,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,1520.2500,0.098870,1.000000,0.000000e+00,0.000000,0.074387,0.000000,1.000000,0.000000,0.000000,0.000000
50%,3039.5000,0.639755,1.000000,1.605906e+18,0.000000,0.513585,0.000000,1.000000,0.000000,0.000000,0.000000
75%,4558.7500,1.309661,1.000000,1.625223e+18,1.000000,1.273395,0.000000,1.000000,0.000000,0.000000,0.000000
max,6078.0000,3.111830,1.000000,1.654498e+18,1.000000,3.111830,1.000000,1.000000,1.000000,1.000000,6109.792079

In [69]:
data2 = data[data['Fill'] == 1]
data2.head()

,Id,Price,Time,State,activo,UTDate,ValidationDate,TimeFrame,Color,High,Stop,Fill,Tested,R1,R2,RMaxima,DateFill,DateStop,DateUltimaR
8,9,0.041720,Fri Oct 25 2019 17:00:00 GMT+0200 (hora de ver...,untested,1,0,Sat Oct 26 2019 02:00:00 GMT+0200 (hora de ver...,1h,blue,1,0.040735,1,0,0,0,0.000000,Wed Oct 23 2019 20:53:00 GMT+0200 (hora de ver...,Wed Oct 23 2019 20:53:00 GMT+0200 (hora de ver...,Thu Jan 01 1970 01:00:00 GMT+0100 (hora estánd...
10,11,0.040165,Fri Oct 25 2019 18:00:00 GMT+0200 (hora de ver...,untested,1,0,Sat Oct 26 2019 15:00:00 GMT+0200 (hora de ver...,1h,blue,0,0.043770,1,0,0,0,0.259362,Sat Oct 26 2019 16:00:00 GMT+0200 (hora de ver...,Mon Oct 28 2019 01:33:00 GMT+0100 (hora estánd...,Thu Jan 01 1970 01:00:00 GMT+0100 (hora estánd...
184,185,0.037470,Mon Dec 02 2019 13:00:00 GMT+0100 (hora estánd...,untested,1,0,Wed Dec 04 2019 01:00:00 GMT+0100 (hora estánd...,4h,green,0,0.038515,1,0,0,0,0.454545,Wed Dec 04 2019 14:22:00 GMT+0100 (hora estánd...,Wed Dec 04 2019 14:24:00 GMT+0100 (hora estánd...,Thu Jan 01 1970 01:00:00 GMT+0100 (hora estánd...
194,195,0.036160,Wed Dec 04 2019 13:00:00 GMT+0100 (hora estánd...,untested,1,0,Tue Dec 10 2019 18:00:00 GMT+0100 (hora estánd...,1h,blue,0,0.039145,1,0,1,0,1.927973,Tue Dec 10 2019 19:00:00 GMT+0100 (hora estánd...,Tue Jan 14 2020 15:15:00 GMT+0100 (hora estánd...,Mon Dec 16 2019 20:49:00 GMT+0100 (hora estánd...
224,225,0.034505,Tue Dec 17 2019 03:00:00 GMT+0100 (hora estánd...,untested,1,0,Wed Dec 18 2019 23:00:00 GMT+0100 (hora estánd...,1h,blue,1,0.030405,1,0,1,1,9.318293,Thu Dec 19 2019 00:00:00 GMT+0100 (hora estánd...,Thu Mar 12 2020 11:47:00 GMT+0100 (hora estánd...,Tue Jan 14 2020 19:13:00 GMT+0100 (hora estánd...

In [70]:
data2.describe()

,Id,Price,activo,UTDate,High,Stop,Fill,Tested,R1,R2,RMaxima
count,201.000000,201.000000,201.0,201.0,201.000000,201.000000,201.0,201.0,201.000000,201.000000,201.000000
mean,2750.572139,0.800568,1.0,0.0,0.616915,0.792175,1.0,0.0,0.597015,0.452736,151.041895
std,1636.177385,0.832954,0.0,0.0,0.487352,0.820755,0.0,0.0,0.491723,0.499004,736.284884
min,9.000000,0.021590,1.0,0.0,0.000000,0.024255,1.0,0.0,0.000000,0.000000,0.000000
25%,1220.000000,0.086935,1.0,0.0,0.000000,0.085200,1.0,0.0,0.000000,0.000000,0.477372
50%,2817.000000,0.507740,1.0,0.0,1.000000,0.520350,1.0,0.0,1.000000,0.000000,1.396813
75%,4271.000000,1.438010,1.0,0.0,1.000000,1.389265,1.0,0.0,1.000000,1.000000,3.392218
max,5983.000000,2.974910,1.0,0.0,1.000000,2.820000,1.0,0.0,1.000000,1.000000,6109.792079